CREATE TABLE IF NOT EXISTS manual_feedback_currents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,
    command_update_id BIGINT NOT NULL,
    content_fingerprint TEXT NOT NULL,
    label VARCHAR(32) NOT NULL,
    category VARCHAR(100) NOT NULL,
    reason VARCHAR(200),
    source VARCHAR(32) NOT NULL,
    revision BIGINT NOT NULL,
    embedding_status VARCHAR(32) NOT NULL,
    embedding_error_code VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT idx_manual_feedback_message UNIQUE (chat_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_manual_feedback_fingerprint
    ON manual_feedback_currents (chat_id, content_fingerprint);

CREATE TABLE IF NOT EXISTS manual_feedback_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    command_update_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    revision BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,
    content_fingerprint TEXT NOT NULL,
    previous_label VARCHAR(32),
    label VARCHAR(32) NOT NULL,
    category VARCHAR(100) NOT NULL,
    reason VARCHAR(200),
    source VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT idx_manual_feedback_command UNIQUE (chat_id, command_update_id),
    CONSTRAINT idx_manual_feedback_revision UNIQUE (chat_id, message_id, revision)
);

CREATE TABLE IF NOT EXISTS manual_feedback_epoch_rows (
    chat_id BIGINT PRIMARY KEY,
    version BIGINT NOT NULL
);
