-- 先啟用既有的 pgvector extension，再執行此 migration。
CREATE TABLE IF NOT EXISTS scoped_manual_feedback_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    revision BIGINT NOT NULL,
    content_fingerprint TEXT NOT NULL,
    embedding_provider VARCHAR(64) NOT NULL,
    embedding_model VARCHAR(200) NOT NULL,
    embedding_version VARCHAR(64) NOT NULL,
    dimensions BIGINT NOT NULL,
    vector VECTOR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT idx_scoped_feedback_embedding UNIQUE
        (chat_id, message_id, revision, embedding_provider, embedding_model, embedding_version, dimensions)
);

CREATE INDEX IF NOT EXISTS idx_scoped_feedback_chat_fingerprint
    ON scoped_manual_feedback_embeddings (chat_id, content_fingerprint);

CREATE INDEX IF NOT EXISTS idx_scoped_manual_feedback_embeddings_expires_at
    ON scoped_manual_feedback_embeddings (expires_at);
