CREATE TABLE IF NOT EXISTS manual_feedback_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    command_update_id BIGINT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    message_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    retryable BOOLEAN NOT NULL,
    error_code VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    CONSTRAINT idx_manual_feedback_action UNIQUE (chat_id, command_update_id, kind)
);
