version: "2026-09-30.1"
rules:
  - id: download_page
    enabled: true
    keywords:
      - 下載頁
      - app 去哪裡下載
      - app 在哪下載
      - 下載 app
      - app 下载
      - app 安装
      - app下載
      - 鲤鱼下载链接
      - 下载链接
      - 下载地址
    reply: "下载页在：https://www.liyuvpn.com"
  - id: official_page
    enabled: true
    keywords:
      - 官方
      - 官方頁
      - 官方页
      - 官方網站
      - 官方网站
      - 官網
      - 官网
      - official page
      - official website
    reply: "官方网站在：https://www.liyuvpn.com"
  - id: support
    enabled: true
    keywords:
      - 客服
      - 聯絡客服
      - 联系客服
    reply: "客服信息：https://www.liyuvpn.com"
